<?php

namespace Configurator\Modules\WC\FSE;

class WC_FSE_Editor_Blocks {

	public static function initialize() : void {
		add_filter( 'unregister_editor_blocks', array( static::class, 'unregister_editor_blocks' ), PHP_INT_MAX, 1 );
		return;
	}

	public static function unregister_editor_blocks( array $blocks ) : array {
		$post_and_site_context_blocks = array(
			'woocommerce/active-filters',
			'woocommerce/product-title',
			'woocommerce/product-price',
			'woocommerce/product-image',
			'woocommerce/product-rating-stars',
			'woocommerce/product-rating-counter',
			'woocommerce/product-average-rating',
			'woocommerce/product-button',
			'woocommerce/product-summary',
			'woocommerce/product-sale-badge',
			'woocommerce/product-sku',
			'woocommerce/product-stock-indicator',
			'woocommerce/all-products',
			'woocommerce/all-reviews',
			'woocommerce/attribute-filter',
			'woocommerce/classic-shortcode',
			'woocommerce/coming-soon',
			'woocommerce/customer-account',
			'woocommerce/featured-category',
			'woocommerce/featured-product',
			'woocommerce/filter-wrapper',
			'woocommerce/handpicked-products',
			'woocommerce/mini-cart',
			'woocommerce/store-notices',
			'woocommerce/price-filter',
			'woocommerce/product-best-sellers',
			'woocommerce/product-categories',
			'woocommerce/product-category',
			'woocommerce/product-collection',
			'woocommerce/product-collection-no-results',
			'woocommerce/product-gallery-large-image',
			'woocommerce/product-new',
			'woocommerce/product-on-sale',
			'woocommerce/product-template',
			'woocommerce/product-search',
			'woocommerce/product-tag',
			'woocommerce/product-top-rated',
			'woocommerce/products-by-attribute',
			'woocommerce/rating-filter',
			'woocommerce/reviews-by-category',
			'woocommerce/reviews-by-product',
			'woocommerce/single-product',
			'woocommerce/stock-filter',
			'woocommerce/page-content-wrapper',
			'woocommerce/filled-cart-block',
			'woocommerce/cart-items-block',
			'woocommerce/cart-line-items-block',
			'woocommerce/cart-cross-sells-block',
			'woocommerce/cart-cross-sells-products-block',
			'woocommerce/cart-totals-block',
			'woocommerce/cart-express-payment-block',
			'woocommerce/proceed-to-checkout-block',
			'woocommerce/empty-cart-block',
			'woocommerce/cart-accepted-payment-methods-block',
			'woocommerce/cart-order-summary-block',
			'woocommerce/cart-order-summary-subtotal-block',
			'woocommerce/cart-order-summary-totals-block',
			'woocommerce/cart-order-summary-fee-block',
			'woocommerce/cart-order-summary-discount-block',
			'woocommerce/cart-order-summary-shipping-block',
			'woocommerce/cart-order-summary-coupon-form-block',
			'woocommerce/cart-order-summary-taxes-block',
			'woocommerce/cart-order-summary-heading-block',
			'woocommerce/cart',
			'woocommerce/checkout-fields-block',
			'woocommerce/checkout-totals-block',
			'woocommerce/checkout-shipping-address-block',
			'woocommerce/checkout-terms-block',
			'woocommerce/checkout-contact-information-block',
			'woocommerce/checkout-billing-address-block',
			'woocommerce/checkout-actions-block',
			'woocommerce/checkout-additional-information-block',
			'woocommerce/checkout-order-note-block',
			'woocommerce/checkout-order-summary-block',
			'woocommerce/checkout-payment-block',
			'woocommerce/checkout-express-payment-block',
			'woocommerce/checkout-shipping-method-block',
			'woocommerce/checkout-shipping-methods-block',
			'woocommerce/checkout-pickup-options-block',
			'woocommerce/checkout-order-summary-subtotal-block',
			'woocommerce/checkout-order-summary-fee-block',
			'woocommerce/checkout-order-summary-discount-block',
			'woocommerce/checkout-order-summary-shipping-block',
			'woocommerce/checkout-order-summary-coupon-form-block',
			'woocommerce/checkout-order-summary-taxes-block',
			'woocommerce/checkout-order-summary-cart-items-block',
			'woocommerce/checkout-order-summary-totals-block',
			'woocommerce/checkout',
			'woocommerce/empty-mini-cart-contents-block',
			'woocommerce/filled-mini-cart-contents-block',
			'woocommerce/mini-cart-title-block',
			'woocommerce/mini-cart-title-items-counter-block',
			'woocommerce/mini-cart-title-label-block',
			'woocommerce/mini-cart-items-block',
			'woocommerce/mini-cart-products-table-block',
			'woocommerce/mini-cart-footer-block',
			'woocommerce/mini-cart-shopping-button-block',
			'woocommerce/mini-cart-cart-button-block',
			'woocommerce/mini-cart-checkout-button-block',
			'woocommerce/mini-cart-contents',
			'woocommerce/product-rating',
			'woocommerce/add-to-cart-form',
			'woocommerce/product-meta',
		);
		$widgets_context_blocks = array(
			'woocommerce/breadcrumbs',
			'woocommerce/catalog-sorting',
			'woocommerce/product-results-count',
			'woocommerce/order-confirmation-status',
			'woocommerce/order-confirmation-summary',
			'woocommerce/order-confirmation-totals',
			'woocommerce/order-confirmation-totals-wrapper',
			'woocommerce/order-confirmation-downloads',
			'woocommerce/order-confirmation-downloads-wrapper',
			'woocommerce/order-confirmation-billing-address',
			'woocommerce/order-confirmation-shipping-address',
			'woocommerce/order-confirmation-billing-wrapper',
			'woocommerce/order-confirmation-shipping-wrapper',
			'woocommerce/order-confirmation-additional-information',
			'woocommerce/order-confirmation-additional-fields-wrapper',
			'woocommerce/order-confirmation-additional-fields',
		);
		$all_contexts = array_merge( $post_and_site_context_blocks, $widgets_context_blocks );
		$blocks = array_merge( $blocks, $all_contexts );
		return $blocks;
	}
}